/**
 * PRD Command - Generate and manage PRDs for Ralph Loop
 *
 * Usage:
 *   bootstralph prd "description of what to build"
 *   bootstralph prd --list
 *   bootstralph prd --status [prd-file]
 */

import * as p from "@clack/prompts";
import * as fs from "fs-extra";
import * as path from "path";
import { execa } from "execa";
import {
  type Prd,
  isPrdComplete,
  getPrdProgress,
  generatePrdFilename,
  generatePrdSlug,
  DEFAULT_COMPLETION_PROMISE,
} from "../ralph/prd-schema.js";

/** Directory where PRDs are stored */
const AGENTS_TASKS_DIR = ".agents/tasks";

/**
 * Ensure the .agents/tasks directory exists
 */
async function ensureTasksDir(): Promise<string> {
  const tasksDir = path.resolve(process.cwd(), AGENTS_TASKS_DIR);
  await fs.ensureDir(tasksDir);
  return tasksDir;
}

/**
 * List all PRD files in the tasks directory
 */
export async function listPrdFiles(): Promise<string[]> {
  const tasksDir = await ensureTasksDir();
  const files = await fs.readdir(tasksDir);
  return files.filter((f) => f.startsWith("prd-") && f.endsWith(".json"));
}

/**
 * Load a PRD from file
 */
export async function loadPrd(filename: string): Promise<Prd | null> {
  const tasksDir = await ensureTasksDir();
  const filepath = path.join(tasksDir, filename);

  if (!(await fs.pathExists(filepath))) {
    return null;
  }

  try {
    const content = await fs.readFile(filepath, "utf-8");
    return JSON.parse(content) as Prd;
  } catch (error) {
    p.log.error(`Failed to parse PRD file: ${filename}`);
    return null;
  }
}

/**
 * Save a PRD to file
 */
export async function savePrd(prd: Prd): Promise<string> {
  const tasksDir = await ensureTasksDir();
  const filename = generatePrdFilename(prd.name);
  const filepath = path.join(tasksDir, filename);

  // Update metadata
  const now = new Date().toISOString();
  prd.metadata = prd.metadata || {};
  prd.metadata.updatedAt = now;
  if (!prd.metadata.createdAt) {
    prd.metadata.createdAt = now;
  }
  if (!prd.metadata.completionPromise) {
    prd.metadata.completionPromise = DEFAULT_COMPLETION_PROMISE;
  }

  await fs.writeFile(filepath, JSON.stringify(prd, null, 2));
  return filepath;
}

/**
 * Create an overview markdown file for a PRD
 */
async function createPrdOverview(prd: Prd): Promise<string> {
  const tasksDir = await ensureTasksDir();
  const slug = generatePrdSlug(prd.name);
  const filename = `prd-${slug}.overview.md`;
  const filepath = path.join(tasksDir, filename);

  const progress = getPrdProgress(prd);
  const incomplete = prd.userStories.filter((s) => !s.passes);
  const complete = prd.userStories.filter((s) => s.passes);

  const content = `# ${prd.name}

> ${prd.description}

## Status: ${prd.status}

**Progress:** ${progress.completed}/${progress.total} stories (${progress.percentage}%)

## User Stories

### Pending (${incomplete.length})
${incomplete
  .map(
    (s) => `
#### ${s.id}: ${s.title}
- Priority: ${s.priority}
- Dependencies: ${s.dependsOn?.join(", ") || "None"}

${s.description}

**Acceptance Criteria:**
${s.acceptanceCriteria.map((c) => `- [ ] ${c}`).join("\n")}
`
  )
  .join("\n")}

### Completed (${complete.length})
${complete.map((s) => `- [x] ${s.id}: ${s.title}`).join("\n") || "None yet"}

---
*Generated by bootstralph*
`;

  await fs.writeFile(filepath, content);
  return filepath;
}

/**
 * Get incomplete PRDs
 */
export async function getIncompletePrds(): Promise<{ filename: string; prd: Prd }[]> {
  const files = await listPrdFiles();
  const results: { filename: string; prd: Prd }[] = [];

  for (const filename of files) {
    const prd = await loadPrd(filename);
    if (prd && !isPrdComplete(prd)) {
      results.push({ filename, prd });
    }
  }

  return results;
}

/**
 * Display status for all PRDs
 */
async function showPrdStatus(specificFile?: string): Promise<void> {
  const files = specificFile ? [specificFile] : await listPrdFiles();

  if (files.length === 0) {
    p.log.info("No PRD files found in .agents/tasks/");
    p.log.info('Create one with: bootstralph prd "your feature description"');
    return;
  }

  for (const filename of files) {
    const prd = await loadPrd(filename);
    if (!prd) continue;

    const progress = getPrdProgress(prd);
    const statusIcon = isPrdComplete(prd) ? "\u2713" : progress.percentage > 0 ? "\u25CB" : "\u25A1";

    p.log.info(`${statusIcon} ${filename}`);
    p.log.message(`   ${prd.name} - ${prd.description}`);
    p.log.message(
      `   Progress: ${progress.completed}/${progress.total} (${progress.percentage}%)`
    );
    p.log.message(`   Status: ${prd.status}`);
  }
}

/**
 * Generate a PRD using Claude Code
 * This runs Claude with the prd-writer skill to generate a PRD from a description
 */
async function generatePrdWithClaude(description: string): Promise<void> {
  const s = p.spinner();

  // Check if we're inside a Docker sandbox or have Claude Code available
  s.start("Preparing to generate PRD...");

  // Ensure tasks directory exists
  await ensureTasksDir();

  // Create the prompt for Claude
  const prompt = `Using the prd-writer skill from .claude/skills/prd-writer/skill.md, create a PRD for the following:

${description}

Requirements:
1. Follow the PRD schema exactly as specified in the skill
2. Create atomic user stories that can each be completed in one Claude iteration
3. Ensure all acceptance criteria are specific and verifiable
4. Set proper dependencies between stories
5. Save the PRD to .agents/tasks/prd-{slug}.json
6. Create an overview file at .agents/tasks/prd-{slug}.overview.md

After creating the PRD, output a summary of:
- PRD name and description
- Number of user stories
- Estimated iterations needed`;

  s.stop("Prompt prepared");

  p.note(
    `Claude will generate a PRD based on:\n"${description}"`,
    "PRD Generation"
  );

  // Try to run Claude Code
  try {
    s.start("Running Claude Code to generate PRD...");

    // Check if we're in a docker sandbox
    const isDocker = await fs.pathExists("/.dockerenv");

    if (isDocker) {
      // Inside docker, run claude directly
      await execa("claude", ["-p", prompt], {
        stdio: "inherit",
        cwd: process.cwd(),
      });
      s.stop("PRD generated");
    } else {
      // Outside docker, suggest using docker sandbox
      s.stop("Claude Code required");
      p.log.warn("PRD generation requires Claude Code.");
      p.log.info("Run this command inside a Docker sandbox:");
      p.log.message(`  docker sandbox run claude -p "${prompt.slice(0, 100)}..."`);
      p.log.info("\nOr run Claude Code directly if installed:");
      p.log.message(`  claude -p "$(cat <<'EOF'\n${prompt}\nEOF\n)"`);

      // Offer to create a template PRD instead
      const createTemplate = await p.confirm({
        message: "Would you like to create a template PRD instead?",
        initialValue: true,
      });

      if (p.isCancel(createTemplate)) {
        p.cancel("Operation cancelled");
        return;
      }

      if (createTemplate) {
        await createTemplatePrd(description);
      }
    }
  } catch (error) {
    s.stop("Failed");
    p.log.error("Failed to run Claude Code.");
    p.log.info("Creating a template PRD instead...");
    await createTemplatePrd(description);
  }
}

/**
 * Create a template PRD that the user can fill in
 */
async function createTemplatePrd(description: string): Promise<void> {
  // Extract a name from the description
  const words = description.split(/\s+/).slice(0, 4);
  const name = words.join(" ");
  const slug = generatePrdSlug(name);

  const templatePrd: Prd = {
    name,
    version: "0.1.0",
    description,
    status: "planning",
    branchName: `feature/${slug}`,
    userStories: [
      {
        id: "US-001",
        title: "Initial setup and configuration",
        description:
          "Set up the initial configuration and dependencies needed for this feature.",
        acceptanceCriteria: [
          "Required dependencies are installed",
          "Configuration file exists",
          "TypeScript compilation succeeds",
        ],
        priority: 1,
        passes: false,
        dependsOn: [],
      },
      {
        id: "US-002",
        title: "Implement core functionality",
        description:
          "Implement the main functionality described in the PRD. Update this description with specific details.",
        acceptanceCriteria: [
          "Core feature is implemented",
          "Unit tests pass",
          "TypeScript compilation succeeds",
        ],
        priority: 2,
        passes: false,
        dependsOn: ["US-001"],
      },
      {
        id: "US-003",
        title: "Add integration tests",
        description:
          "Write integration tests to verify the feature works end-to-end.",
        acceptanceCriteria: [
          "Integration tests exist",
          "All tests pass",
          "Code coverage meets threshold",
        ],
        priority: 3,
        passes: false,
        dependsOn: ["US-002"],
      },
    ],
    metadata: {
      createdAt: new Date().toISOString(),
      completionPromise: DEFAULT_COMPLETION_PROMISE,
    },
  };

  const filepath = await savePrd(templatePrd);
  const overviewPath = await createPrdOverview(templatePrd);

  p.log.success(`Created template PRD: ${filepath}`);
  p.log.info(`Overview: ${overviewPath}`);
  p.log.info("\nEdit the PRD to add specific user stories and acceptance criteria.");
  p.log.info("Then run: bootstralph ralph");
}

/**
 * Handle the 'prd' command
 */
export async function handlePrd(args: string[]): Promise<void> {
  p.intro("bootstralph prd - PRD Management");

  // Parse flags
  const listFlag = args.includes("--list") || args.includes("-l");
  const statusFlag = args.includes("--status") || args.includes("-s");

  if (listFlag) {
    await showPrdStatus();
    return;
  }

  if (statusFlag) {
    const statusIndex = args.findIndex((a) => a === "--status" || a === "-s");
    const specificFile = args[statusIndex + 1];
    await showPrdStatus(specificFile?.startsWith("-") ? undefined : specificFile);
    return;
  }

  // Get description from args or prompt
  const description = args.filter((a) => !a.startsWith("-")).join(" ");

  if (!description) {
    const descResult = await p.text({
      message: "What would you like to build?",
      placeholder: "Add user authentication with better-auth",
      validate: (value) => {
        if (!value || value.length < 10) {
          return "Please provide a description of at least 10 characters";
        }
        return undefined;
      },
    });

    if (p.isCancel(descResult)) {
      p.cancel("Operation cancelled");
      return;
    }

    await generatePrdWithClaude(descResult);
  } else {
    await generatePrdWithClaude(description);
  }

  p.outro("PRD command complete");
}
